-- Creation of Table Plus Reservés --
CREATE TABLE IF NOT EXISTS Reservés (
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(225) NOT NULL,
description TEXT,
image_url VARCHAR(255) NOT NULL,
price DECIMAL(10,2) DEFAULT NULL,
discount DECIMAL(10,2) DEFAULT NULL,
Star INT DEFAULT 0, 
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);