CREATE TABLE IF NOT EXISTS reservations (
id INT AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(255) NOT NULL,
prenom VARCHAR(255) NOT NULL,
localisation VARCHAR(255) NOT NULL,
price DECIMAL(10,2) NOT NULL,
status ENUM('pending','confirmed','cancelled') DEFAULT 'confirmed',
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);